spring.application.name=ru.rgs.messagesender

server.port=8081

queue.name = SOI.OUTPUT
queue.exchange = SOI
queue.routingKey= SOI.OUTPUT

rmq.addresses=172.18.0.2:5672,172.18.0.3:5672,172.18.0.4:5672
rmq.username=admin
rmq.password=admin
#rmq.hostname=172.18.0.2
#rmq.port=5672
rmq.virtualHost=/

logging.level.ru.rgs.messagesender.jms.RmqCommonConfig=DEBUG
logging.level.ru.rgs.messagesender.jms.RmqCommon=DEBUG

server.chunkedMaxContentLength = 10000

camel.springboot.xmlRoutes = file:config/routes/*.xml
camel.springboot.xmlRests = file:config/rests/*.xml



#No auth  protected
endpoints.shutdown.sensitive=false
#Enable shutdown endpoint
endpoints.shutdown.enabled=true

camel.springboot.routes-include-pattern=file:config/routes/**

timer.period = 10000000
maxcount = 10000
threadsCount = 3

correlationId = 4367817B-F83B-E759-E063-11ECDD0A6229




