spring.application.name=ru.rgs.messagesender

server.port=8081

timer.period = 1000000
queue.name = KIAS.OUTPUT
queue.exchange = KIAS
queue.routingKey= KIAS.OUTPUT

rabbitmq.hosts=10.240.247.31:5672,10.240.247.32:5672,10.240.247.33:5672
rabbitmq.username=ESB_TEST
rabbitmq.password=12345

server.chunkedMaxContentLength = 10000

camel.springboot.xmlRoutes = file:config/routes/*.xml
camel.springboot.xmlRests = file:config/rests/*.xml

#No auth  protected
endpoints.shutdown.sensitive=false
#Enable shutdown endpoint
endpoints.shutdown.enabled=true

camel.springboot.routes-include-pattern=file:config/routes/**

maxcount = 1
threadsCount = 3

correlationId = 11111116-F83B-E759-E063-11ECDD0A6229
bodyContentPath="C:\Users\MKurtsman\work\messagesender\src\main\resources\body.xml"




