spring.application.name=ru.rgs.messagesender

server.port=8081

queue.name = SOI.OUTPUT
queue.exchange = SOI
queue.routingKey= SOI.OUTPUT

rabbitmq.hosts=172.18.0.2:5672,172.18.0.3:5672,172.18.0.4:5672
rabbitmq.username=guest
rabbitmq.password=guest

server.chunkedMaxContentLength = 10000

camel.springboot.xmlRoutes = file:config/routes/*.xml
camel.springboot.xmlRests = file:config/rests/*.xml



#No auth  protected
endpoints.shutdown.sensitive=false
#Enable shutdown endpoint
endpoints.shutdown.enabled=true

camel.springboot.routes-include-pattern=file:config/routes/**

timer.period = 10000000
maxcount = 10000
threadsCount = 3

correlationId = 4367817B-F83B-E759-E063-11ECDD0A6229




